### ISSUE TITLE
Difference from previous apres calcul baseline

### ISSUE THREAD

**Issue by SolennTissier** [S-Belanger/Umit#12]
![image](https://user-images.githubusercontent.com/72576370/137926825-1ad4d875-8848-4cfc-8d34-c67a257b37e8.png)

Array indices must be positive integers or logical values.

Error in PlotCorrMatrix/updateData/changeDat (line 344)
                        in(idx_g) = tmp(ib);

Error in PlotCorrMatrix/updateData (line 319)
                app.data = changeDat(app.data, Mat_dispType);

Error in PlotCorrMatrix/ShowMatrixasDropDownValueChanged (line 400)
            app.updateData;
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 378)
Error while evaluating DropDown PrivateValueChangedFcn.

**Comment by BrunoOFSouza** [comment]
Fixed in 0c921eb431241e3e58893d12f526649da6e674b5
