### ISSUE TITLE
ROIs are not excluded or edited by mask

### ISSUE THREAD

**Issue by SolennTissier** [S-Belanger/Umit#16]
![image](https://user-images.githubusercontent.com/72576370/142891971-c97483a7-7a00-4e7d-9565-3367439e9532.png)

**Comment by S-Belanger** [comment]
1- Bug should be reported in English
2- More details should be given with the bug report. Not just a screenshot like this. 

Thank you

**Comment by SolennTissier** [comment]
copy that

**Comment by BrunoOFSouza** [comment]
@SolennTissier , I couldn't replicate the bug.
Could you share here the data from the image above as a ***.mat***  file? 
Thanks

**Comment by BrunoOFSouza** [comment]
Actually, the app will only detect and exclude areas in the image containing ***NaNs***. In your case, the mask (blue region outside the brain) is composed of zeros. That is why it doesn't work.
