### ISSUE TITLE
Fonction DF/F pour rétino 

### ISSUE THREAD

**Issue by SolennTissier** [S-Belanger/Umit#17]
![image](https://user-images.githubusercontent.com/72576370/142892100-8c8c1c04-85c0-415f-82bd-62f39545196f.png)
![image](https://user-images.githubusercontent.com/72576370/142892136-8703e6c2-8a32-4c83-9d41-3a79796ce222.png)

**Comment by S-Belanger** [comment]
Is there any good reasons to do a frequency filter on Retino data since we then do a Fourier Transform? Doesn't make sense to me...

(Also, please repport the bugs in English)
