### ISSUE TITLE
Unrecognized field name "name".

### ISSUE THREAD

**Issue by G-Laliberte** [S-Belanger/Umit#18]
Hi, 
I try to use the sandalone DataViewer on my 3-channels visual stimulation acquisition. I have no issue opening the GUI but when I tried to ''Import Raw Data'' in the File tab I received these errors:

_

> Unrecognized field name "name".
> 
> Error in DataViewer_pipelineMngr/check_funcName (line 328)
>                 idx_fcn = strcmp(func, {obj.funcList.name});
> 
> Error in DataViewer_pipelineMngr/setOpts (line 68)
>             [b_OK, idx] = obj.check_funcName(func);
> 
> Error in DataViewer/ImportRawdataMenuSelected (line 1322)
>             ppln.setOpts('run_ImagesClassification');
>  
> Error using matlab.ui.internal.controller.WebMenuController/fireActionEvent (line 67)
> Error while evaluating Menu Callback.

_

I tried to rename my folder with this following order : MouseID_EyeStimulated_Stimulation_Date as I think Solenn is doing. However, I got the same errors. Do you have any idea what I might do wrong?

thanks,

**Comment by BrunoOFSouza** [comment]
Hi Guillaume!
This could be a *Path* issue. Did you follow the installation instructions in the wiki? 
If so, could you run again the function ```Umitoolbox_setupEnv.m```?
It should display the message *'Environment Variable Umitoolbox already exists!'*

Let me know what happens.

**Comment by G-Laliberte** [comment]
Yes I created the Umitoolbox folder, put the DataViewer standalone GitHub Branch in it, as well as the IOI_Ana-master folder. 
As I'm using WIndows, I ran the function Umitoolbox_setupEnv.m before trying to Import my data. 

Currently, I receive this message when I run the Umitoolbox_setupEnv function 

`Environment Variable Umitoolbox already exists!`

**Comment by BrunoOFSouza** [comment]
Good! I'll take a look at the data that you just sent me. Give you a feedback soon!

**Comment by BrunoOFSouza** [comment]
@G-Laliberte , I think I fixed the issue (see commit c27ead3ab2def3d3e508f4bd6aab064ccc0a1396).
The problem was that a couple of ***regexp*** functions were not behaving the same way in Matlab's version R2021a (your version) and R2019a (mine). This created an empty structure instead of a structure array containing the information of the available analysis functions inside ***DataViewer_pipelineMngr.m***.

Please let me know if you encounter other problems.

**Comment by G-Laliberte** [comment]
It works, 

thank you!
