### ISSUE TITLE
Nodeobj doesn't exist

### ISSUE THREAD

**Issue by VeroniqueChouinard** [S-Belanger/Umit#25]
The following error appears when trying to select any acquisitions on the Dashboard. 
![image](https://user-images.githubusercontent.com/72818203/161623664-ff58e416-7e6c-4c3a-ba4d-08b7bdac4ad4.png)

**Comment by BrunoOFSouza** [comment]
Fixed in commit 1ffa87b03caf90fd02b53b7fbf93674348808999
