### ISSUE TITLE
unable to load statsgroups 

### ISSUE THREAD

**Issue by VeroniqueChouinard** [S-Belanger/Umit#26]
Following error when trying to load a previously saved statsgroup.mat in the grouping tool of the Analysis component : 
![image](https://user-images.githubusercontent.com/72818203/161641737-493b936d-3342-4ffd-8c5f-241398033674.png)

**Comment by BrunoOFSouza** [comment]
@VeroniqueChouinard , could you send me the *statsgroup.mat* file?
I'll try to replicate the problem.

**Comment by BrunoOFSouza** [comment]
I fixed the issue using a new statsgroup file. @VeroniqueChouinard , let me know if the problem persists using old statsgroup files.

**Comment by VeroniqueChouinard** [comment]
The problem is still there with old groups. However, it works with new groups.
I'm also having a second problem with the creation of groups; some acquisition don't change groups when I try to move them from the base or from another group : it's as if the input wasn't sent. There is no error on Matlab; only «Verifying duplicates...».

**Comment by BrunoOFSouza** [comment]
I see. Can you send me one of the faulty statsgroup file?

**Comment by BrunoOFSouza** [comment]
The faulty old *statsgroup files* inherited an error from a bug probably fixed in the recent commit 76723ea847c07ef188b9cafece2f127582563622.
To fix the *statsgroup* file to this:
1. Load the file content in Matlab`s workspace.
2. type: 
```groupInfo.Ngroups = length(groupInfo.gIdxList)```
3. Save the structure **groupInfo** to the statsgroup file:
``` save('FULLPATH_TO_STATSFILE', 'groupInfo')```
