### ISSUE TITLE
Error when trying advanced search with modality presets

### ISSUE THREAD

**Issue by VeroniqueChouinard** [S-Belanger/Umit#29]
![image](https://user-images.githubusercontent.com/72818203/167453507-fb185f61-9ddf-44f5-8cdc-b5f1aa112cf7.png)

Parameters of the search builder : 
![image](https://user-images.githubusercontent.com/72818203/167454076-bd17bda3-b543-4858-8786-91e15894dafa.png)

**Comment by BrunoOFSouza** [comment]
Fixed in commit ac86436da8d54eda3482709f44570e40d131096f

The app wasn't working with numeric values. Now, it should work.
