### ISSUE TITLE
Bug on image option on any fluo.dat file in DataViewer

### ISSUE THREAD

**Issue by VeroniqueChouinard** [S-Belanger/Umit#31]
I tried viewing on two different resting state acquisition in DataViewer either the fluo.dat file or the .dat after temporal filtering and everytime I press settings> Image options: It loads for a minute and then the error «Out of memory» appear. However, the memory of my PC is not used over 50% and during the loading the % of used memory does not seemed to go higher.

The function works well only with DeltaF_F_ByEvent.dat

**Comment by BrunoOFSouza** [comment]
Ok. I'll try to replicate the bug. 
Could you send me the .mat file associated with the *fluo.dat* file?

**Comment by BrunoOFSouza** [comment]
Fixed in commit f18a99b9dfd543a3955deea39a56458d848bf6ea
