### ISSUE TITLE
[BUG] - analysis Corr Matrix. 

### ISSUE THREAD

**Issue by Zak-Eckert** [S-Belanger/Umit#37]
Hello, 
I have been trying to generate a correlation matrix which uses multiple baselines from multiple animals, then compares it against a post stroke model to determine alterations in atlas assigned regions following stroke. However, I have run into the issue which will not allow it to alter the number of baseline maps. The error is stated as followed: 

Error using cat
Dimensions of arrays being concatenated are not consistent.

Error in PlotCorrMatrix/updateData (line 299)
                app.data(i).MatData.data = mean(cat(4,app.matrix_struct(idx).data),4,'omitnan');

Error in PlotCorrMatrix/SetbaselineButtonPushed (line 520)
            app.updateData;
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 410)
Error while evaluating Button PrivateButtonPushedFcn.

I was wondering if there is a solution to this, or if there is something that can be done about it. I have also attached an image to see what my error point was

![Capture](https://user-images.githubusercontent.com/101667936/181600949-a5501ebb-ca9d-49cf-93b9-4cfad6400283.PNG)

**Comment by BrunoOFSouza** [comment]
@Zak-Eckert , 
Thanks for flagging this issue. 
It seems that the app fails to average acquisitions with different number of recordings (2 vs 1, in your case). 

We will work on it to fix this bug.

**Comment by BrunoOFSouza** [comment]
The issue was fixed in commit 72b752b3e29dc817b8215cf51016d2110ca37080.
The bug was caused when trying to merge two or more acquisitions as a *baseline*.
More precisely, the bug occurred when Matlab tried to concatenate one correlation matrix with dimension N x N (one *R*ecording) with another with dimensions N x N x R (with two or more recordings) .
